import { Resource } from '../../../shared/form-schema';
import { lookup, nameField } from '../../usuarios-catalogo/application/resources';
const base = '/organization';
export const organizationResources: Resource[] = [
  {
    key: 'suppliers',
    title: 'Proveedores',
    singular: 'proveedor',
    path: `${base}/suppliers`,
    group: 'Organización',
    permission: 'suppliers.read',
    writePermission: 'suppliers.write',
    states: true,
    softDelete: true,
    search: true,
    columns: [
      { key: 'business_name', label: 'Razón social' },
      { key: 'tax_id', label: 'NIT' },
      { key: 'contact_name', label: 'Contacto' },
      { key: 'phone', label: 'Teléfono' },
    ],
    fields: [
      { key: 'business_name', label: 'Razón social', required: true, minLength: 2, maxLength: 180 },
      { key: 'trade_name', label: 'Nombre comercial', maxLength: 180 },
      { key: 'tax_id', label: 'NIT', required: true, minLength: 3, maxLength: 50 },
      { key: 'contact_name', label: 'Persona de contacto', maxLength: 150 },
      { key: 'email', label: 'Correo', type: 'email' },
      { key: 'phone', label: 'Teléfono', maxLength: 30 },
      { key: 'address', label: 'Dirección', maxLength: 255 },
      { key: 'city', label: 'Ciudad', maxLength: 100 },
      { key: 'notes', label: 'Notas', type: 'textarea' },
    ],
  },
  {
    key: 'cities',
    title: 'Ciudades',
    singular: 'ciudad',
    path: `${base}/cities`,
    group: 'Organización',
    permission: 'branches.read',
    writePermission: 'branches.write',
    states: true,
    columns: [
      { key: 'name', label: 'Ciudad' },
      { key: 'department', label: 'Departamento' },
      { key: 'country', label: 'País' },
    ],
    fields: [
      nameField,
      { ...nameField, key: 'department', label: 'Departamento' },
      { ...nameField, key: 'country', label: 'País', default: 'Bolivia' },
    ],
  },
  {
    key: 'branches',
    title: 'Sucursales',
    singular: 'sucursal',
    path: `${base}/branches`,
    group: 'Organización',
    permission: 'branches.read',
    writePermission: 'branches.write',
    states: true,
    softDelete: true,
    columns: [
      { key: 'code', label: 'Código' },
      { key: 'name', label: 'Sucursal' },
      { key: 'city', label: 'Ciudad' },
      { key: 'address', label: 'Dirección' },
    ],
    fields: [
      { key: 'code', label: 'Código', required: true, minLength: 2, maxLength: 30 },
      { ...nameField, maxLength: 150 },
      lookup('city_id', 'Ciudad', `${base}/cities`, true),
      { key: 'address', label: 'Dirección', required: true, minLength: 5, maxLength: 255 },
      { key: 'phone', label: 'Teléfono', maxLength: 30 },
      { key: 'latitude', label: 'Latitud', type: 'number', min: -90, max: 90 },
      { key: 'longitude', label: 'Longitud', type: 'number', min: -180, max: 180 },
      { key: 'opening_hours', label: 'Horarios de atención', type: 'hours' },
    ],
  },
  {
    key: 'cash-points',
    title: 'Cajas',
    singular: 'caja',
    path: `${base}/cash-points`,
    group: 'Organización',
    permission: 'branches.read',
    writePermission: 'branches.write',
    states: true,
    softDelete: true,
    columns: [
      { key: 'code', label: 'Código' },
      { key: 'name', label: 'Caja' },
      { key: 'branch_id', label: 'Sucursal' },
    ],
    fields: [
      lookup('branch_id', 'Sucursal', `${base}/branches`, true),
      { key: 'code', label: 'Código', required: true, maxLength: 30 },
      nameField,
    ],
  },
];
